# Generated by Django 4.2.7 on 2023-12-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_parts_rename_group_bike_delete_musician_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='albums/')),
                ('release_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='parts',
            name='types',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
