# Generated by Django 4.2.7 on 2023-12-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_staff_delete_album_parts_types_alter_bike_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('types', models.CharField(max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='albums/')),
            ],
        ),
        migrations.CreateModel(
            name='HandleBars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='albums/')),
            ],
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
