# Generated by Django 4.2.7 on 2023-12-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_rename_description_handlebars_types_frames_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frames',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
