# Generated by Django 4.2.7 on 2023-12-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_cranks_wheels_delete_contract_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cranks',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='handlebars',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wheels',
            old_name='Name',
            new_name='name',
        ),
    ]
