# Generated by Django 4.2.7 on 2024-01-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_rename_name_cranks_name_rename_name_handlebars_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='name',
            new_name='Bname',
        ),
    ]
