# Generated by Django 4.2.7 on 2024-01-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_rename_name_bike_bname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cranks',
            old_name='name',
            new_name='Cname',
        ),
        migrations.RenameField(
            model_name='frames',
            old_name='name',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='handlebars',
            old_name='name',
            new_name='Hname',
        ),
        migrations.RemoveField(
            model_name='wheels',
            name='name',
        ),
        migrations.AddField(
            model_name='wheels',
            name='Wname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
