# Generated by Django 4.2.7 on 2024-01-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_rename_name_cranks_cname_rename_name_frames_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Bike/'),
        ),
    ]
