# Generated by Django 4.2.7 on 2024-01-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_cranks_handlebars_frames_bike_handlebars_frames_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cranks',
            name='HandleBars',
        ),
        migrations.RemoveField(
            model_name='frames',
            name='Fname',
        ),
        migrations.RemoveField(
            model_name='handlebars',
            name='Hname',
        ),
        migrations.RemoveField(
            model_name='handlebars',
            name='frames',
        ),
        migrations.RemoveField(
            model_name='wheels',
            name='HandleBars',
        ),
        migrations.AddField(
            model_name='cranks',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.bike'),
        ),
        migrations.AddField(
            model_name='handlebars',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.bike'),
        ),
        migrations.AddField(
            model_name='wheels',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.bike'),
        ),
    ]
