# Generated by Django 4.2.7 on 2024-01-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_remove_cranks_handlebars_remove_frames_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='Bname',
            new_name='Bike_name',
        ),
        migrations.RenameField(
            model_name='cranks',
            old_name='Cname',
            new_name='Crank_name',
        ),
        migrations.RenameField(
            model_name='wheels',
            old_name='Wname',
            new_name='Wheel_name',
        ),
        migrations.AddField(
            model_name='frames',
            name='Frame_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='handlebars',
            name='Handlebar_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
