# Generated by Django 4.2.7 on 2024-01-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_rename_bike_name_bike_bname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cranks',
            name='bike',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.bike'),
        ),
        migrations.AlterField(
            model_name='handlebars',
            name='bike',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.bike'),
        ),
        migrations.AlterField(
            model_name='wheels',
            name='bike',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.bike'),
        ),
    ]
