# Generated by Django 4.2.7 on 2024-01-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_cranks_bike_alter_handlebars_bike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cranks',
            name='wheels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.wheels'),
        ),
        migrations.AddField(
            model_name='handlebars',
            name='frames',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.frames'),
        ),
        migrations.AddField(
            model_name='wheels',
            name='handlebars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.handlebars'),
        ),
        migrations.AlterField(
            model_name='cranks',
            name='media_file',
            field=models.FileField(blank=True, upload_to='cranks/'),
        ),
    ]
