# Generated by Django 4.2.7 on 2024-01-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_rename_name_bike_bike_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frames',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='handlebars',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='handlebars',
            name='frames',
        ),
        migrations.RemoveField(
            model_name='wheels',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='wheels',
            name='handlebars',
        ),
    ]
