# Generated by Django 4.2.7 on 2024-01-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_remove_frames_bike_remove_handlebars_bike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frames',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.bike'),
        ),
        migrations.AddField(
            model_name='handlebars',
            name='bike',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.bike'),
        ),
        migrations.AddField(
            model_name='handlebars',
            name='frames',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.frames'),
        ),
        migrations.AddField(
            model_name='wheels',
            name='bike',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.bike'),
        ),
        migrations.AddField(
            model_name='wheels',
            name='handlebars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.handlebars'),
        ),
    ]
