# Generated by Django 4.2.7 on 2024-01-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_frames_bike_handlebars_bike_handlebars_frames_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handlebars',
            name='frames',
        ),
        migrations.RemoveField(
            model_name='wheels',
            name='handlebars',
        ),
    ]
