# Generated by Django 4.2.7 on 2024-01-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_remove_handlebars_frames_remove_wheels_handlebars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cranks',
            old_name='crank_name',
            new_name='cranks_name',
        ),
    ]
