# Generated by Django 4.2.7 on 2024-01-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_rename_crank_name_cranks_cranks_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('terms', models.TextField(blank=True)),
                ('payment', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=35, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_started', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Victor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victor_name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('score', models.IntegerField(null=True)),
                ('media_file', models.ImageField(blank=True, upload_to='media_file/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('jersey', models.IntegerField(null=True)),
                ('player_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='CourtContractStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('D', 'Denied')], max_length=1)),
                ('contract', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.contract')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.team')),
            ],
        ),
    ]
