# Generated by Django 5.0.1 on 2024-01-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_rename_cranks_name_cranks_cname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handlebars',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='wheels',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='cranks',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='frames',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='courtcontractstatus',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='courtcontractstatus',
            name='team',
        ),
        migrations.RemoveField(
            model_name='cranks',
            name='wheels',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_name',
        ),
        migrations.DeleteModel(
            name='Victor',
        ),
        migrations.DeleteModel(
            name='HandleBars',
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
        migrations.DeleteModel(
            name='Frames',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='CourtContractStatus',
        ),
        migrations.DeleteModel(
            name='Cranks',
        ),
        migrations.DeleteModel(
            name='Wheels',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
