# Generated by Django 3.2.24 on 2024-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0031_remove_handlebars_bike_remove_wheels_bike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('message', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'FP_Review',
            },
        ),
    ]
