# Generated by Django 3.2.24 on 2024-02-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_review'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
